// server/src/services/import/tiptap/documentIRToTiptap.js
import { generateJSON } from '@tiptap/html';
import StarterKit from '@tiptap/starter-kit';
import { Image } from '@tiptap/extension-image';
import { Table } from '@tiptap/extension-table';
import { TableRow } from '@tiptap/extension-table-row';
import { TableHeader } from '@tiptap/extension-table-header';
import { Underline } from '@tiptap/extension-underline';
import { TextAlign } from '@tiptap/extension-text-align';
import { Superscript } from '@tiptap/extension-superscript';
import { Subscript } from '@tiptap/extension-subscript';
import { Link } from '@tiptap/extension-link';
import { TextStyle } from '@tiptap/extension-text-style';
import { FontFamily } from '@tiptap/extension-font-family';
import { Color } from '@tiptap/extension-color';
import { Highlight } from '@tiptap/extension-highlight';
import { FontSize, LineSpacing, Indentation, HorizontalRule, CustomTableCell } from './customExtensions.js';
import sanitizeHtml from 'sanitize-html';
import * as cheerio from 'cheerio';

export const getTiptapExtensions = () => [
  StarterKit.configure({
    // Disable extensions bundled in StarterKit v3 that we register
    // explicitly below with custom configuration/attributes
    horizontalRule: false,
    link: false,
    underline: false,
  }),
  Image,
  Table.configure({ resizable: true }),
  TableRow,
  TableHeader,
  CustomTableCell,
  Underline,
  Superscript,
  Subscript,
  Link.configure({
    openOnClick: false,
    autolink: true,
  }),
  TextStyle,
  FontFamily,
  Color,
  Highlight.configure({ multicolor: true }),
  FontSize,
  LineSpacing,
  Indentation,
  HorizontalRule,
  TextAlign.configure({ types: ['heading', 'paragraph'] }),
];

export class DocumentIRToTiptap {
  /**
   * Converts HTML string and asset URLs to Tiptap JSON Schema
   * @param {Object} data
   * @param {string} data.html - The raw HTML generated by Mammoth/LibreOffice
   * @param {Map<string, string>} assetUrlMap - Map of assetId -> resolved storage URL
   * @returns {{ tiptapJson: Object, contentHtml: string, plainText: string, pageLayout: Object }}
   */
  convert({ html }, assetUrlMap = new Map()) {
    const pageLayout = { size: null, margin: null };
    
    // 0. Extract page layout from LibreOffice @page CSS if present
    const pageStyleMatch = html.match(/@page\s*{([^}]+)}/i);
    if (pageStyleMatch) {
      const pageProps = pageStyleMatch[1];
      const sizeMatch = pageProps.match(/size:\s*([^;]+)/i);
      const marginMatch = pageProps.match(/margin:\s*([^;]+)/i);
      if (sizeMatch) pageLayout.size = sizeMatch[1].trim();
      if (marginMatch) pageLayout.margin = marginMatch[1].trim();
    }
    // 1. Replace data-asset-id with real URLs using Cheerio for robustness
    const $img = cheerio.load(html, null, false);
    $img('img').each(function() {
      const assetId = $img(this).attr('data-asset-id');
      if (assetId && assetUrlMap.has(assetId)) {
        $img(this).attr('src', assetUrlMap.get(assetId));
        $img(this).removeAttr('data-asset-id');
      }
    });

     // Preserve heading semantics from DOCX for document outline fidelity
     // (Previously converted all headings to <p>, destroying structure)
     
     const processedHtml = $img.html();

    // 2. Sanitize HTML
    let cleanHtml;
    try {
      cleanHtml = sanitizeHtml(processedHtml, {
        allowedTags: sanitizeHtml.defaults.allowedTags.concat([
          'img', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 's', 'u', 'a',
          'table', 'thead', 'tbody', 'colgroup', 'col', 'tr', 'th', 'td', 'hr',
          'ul', 'ol', 'li', 'blockquote', 'sup', 'sub', 'figcaption', 'mark'
        ]),
        allowedAttributes: {
          ...sanitizeHtml.defaults.allowedAttributes,
          a: ['href', 'title', 'target'],
          img: ['src', 'alt', 'width', 'height'],
          th: ['colspan', 'rowspan', 'style', 'data-bg-color', 'data-border-color'],
          td: ['colspan', 'rowspan', 'style', 'data-bg-color', 'data-border-color'],
          col: ['style', 'width'],
          p: ['style', 'class'],
          span: ['style', 'class'],
          hr: ['class'],
          h1: ['style', 'class'],
          h2: ['style', 'class'],
          h3: ['style', 'class'],
          h4: ['style', 'class'],
          h5: ['style', 'class'],
          h6: ['style', 'class'],
          mark: ['style', 'data-color'],
        },
        allowedSchemes: ['http', 'https', 'data'],
      });
    } catch (e) {
      throw new Error(`Sanitization failed: ${e.message}`);
    }

    // 3. Normalization (Req 8)
    try {
      const $ = cheerio.load(cleanHtml, null, false);
      
      // Collapse runs of 3+ consecutive empty paragraphs to 2
      // (DOCX uses empty paragraphs for intentional spacing; preserve them)
      const allParagraphs = $('p').toArray();
      let consecutiveEmpty = 0;
      for (const el of allParagraphs) {
        const text = $(el).text().trim();
        const hasImg = $(el).find('img').length > 0;
        if (text === '' && !hasImg) {
          consecutiveEmpty++;
          if (consecutiveEmpty > 2) {
            $(el).remove();
          }
        } else {
          consecutiveEmpty = 0;
        }
      }
      
      // Handle LibreOffice Page Breaks (usually inline style page-break-before: always)
      $('*[style*="page-break-before"]').each(function() {
        const style = $(this).attr('style');
        if (style && (style.includes('page-break-before: always') || style.includes('page-break-before:always'))) {
           $(this).before('<hr class="page-break">');
           // Remove the style so it doesn't cause issues
           $(this).attr('style', style.replace(/page-break-before\s*:\s*always;?/i, ''));
        }
      });

      // Remove inline styles we don't support, keep text-align and formatting
      $('[style]').each(function() {
        const style = $(this).attr('style');
        if (style) {
          const supportedStyles = [];
          const styles = style.split(';').map(s => s.trim()).filter(Boolean);
          styles.forEach(s => {
            if (
              s.startsWith('text-align') ||
              s.startsWith('font-family') ||
              s.startsWith('font-size') ||
              s.startsWith('color') ||
              s.startsWith('line-height') ||
              s.startsWith('margin-top') ||
              s.startsWith('margin-bottom') ||
              s.startsWith('margin-left') ||
              s.startsWith('margin-right') ||
              s.startsWith('text-indent') ||
              s.startsWith('font-weight') ||
              s.startsWith('font-style') ||
              s.startsWith('text-decoration') ||
              s.startsWith('background-color') ||
              s.startsWith('vertical-align') ||
              s.startsWith('border-color') ||
              s.startsWith('border')
            ) {
              supportedStyles.push(s);
            }
          });
          
          if (supportedStyles.length > 0) {
            $(this).attr('style', supportedStyles.join('; '));
          } else {
            $(this).removeAttr('style');
          }
        }
      });
      
      // Convert Mammoth alignment classes to Tiptap text-align styles
      $('.align-center').css('text-align', 'center').removeClass('align-center');
      $('.align-right').css('text-align', 'right').removeClass('align-right');
      $('.align-justify').css('text-align', 'justify').removeClass('align-justify');

      cleanHtml = $.html();
    } catch (e) {
      console.warn('[DocumentIRToTiptap] Normalization warning:', e.message);
    }

    // 4. Generate Tiptap JSON
    let tiptapJson;
    try {
      tiptapJson = generateJSON(cleanHtml, getTiptapExtensions());
      
      // Ensure at least one paragraph exists if empty (Tiptap schema requirement)
      if (!tiptapJson.content || tiptapJson.content.length === 0) {
        tiptapJson.content = [{ type: 'paragraph' }];
      }
    } catch (e) {
      throw new Error(`Tiptap conversion failed: ${e.message}`);
    }
    
    // 5. Extract plain text
    const extractText = (node) => {
      let text = '';
      if (node.type === 'text') {
        text += node.text;
      } else if (node.type === 'image') {
        text += ' [Image] ';
      }
      if (node.content) {
        node.content.forEach((child) => {
          text += extractText(child);
        });
      }
      if (node.type === 'paragraph' || node.type?.startsWith('heading')) {
        text += '\n\n';
      }
      return text;
    };

    const plainText = extractText(tiptapJson).trim();

    return {
      tiptapJson,
      contentHtml: cleanHtml,
      plainText,
      pageLayout
    };
  }
}

export default DocumentIRToTiptap;
