version: '3'
services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice_poc
    ports:
      - "8080:80"
    environment:
      - JWT_SECRET=super_secret_key_123
      - JWT_ENABLED=true
    restart: always
