// server/src/services/import/tiptap/documentIRToTiptap.js
import { generateJSON } from '@tiptap/html';
import StarterKit from '@tiptap/starter-kit';
import { Image } from '@tiptap/extension-image';
import { Table } from '@tiptap/extension-table';
import { TableRow } from '@tiptap/extension-table-row';
import { TableHeader } from '@tiptap/extension-table-header';
import { TableCell } from '@tiptap/extension-table-cell';
import { Underline } from '@tiptap/extension-underline';
import { TextAlign } from '@tiptap/extension-text-align';
import { Superscript } from '@tiptap/extension-superscript';
import { Subscript } from '@tiptap/extension-subscript';
import sanitizeHtml from 'sanitize-html';
import * as cheerio from 'cheerio';

export const getTiptapExtensions = () => [
  StarterKit,
  Image,
  Table,
  TableRow,
  TableHeader,
  TableCell,
  Underline,
  Superscript,
  Subscript,
  TextAlign.configure({ types: ['heading', 'paragraph'] }),
];

export class DocumentIRToTiptap {
  /**
   * Converts HTML string and asset URLs to Tiptap JSON Schema
   * @param {Object} data
   * @param {string} data.html - The raw HTML generated by Mammoth
   * @param {Map<string, string>} assetUrlMap - Map of assetId -> resolved storage URL
   * @returns {{ tiptapJson: Object, contentHtml: string, plainText: string }}
   */
  convert({ html }, assetUrlMap = new Map()) {
    // 1. Replace data-asset-id with real URLs
    let processedHtml = html;
    assetUrlMap.forEach((url, assetId) => {
      const regex = new RegExp(`src="[^"]+"\\s+data-asset-id="${assetId}"`, 'g');
      processedHtml = processedHtml.replace(regex, `src="${url}"`);
    });

    // 2. Sanitize HTML
    let cleanHtml;
    try {
      cleanHtml = sanitizeHtml(processedHtml, {
        allowedTags: sanitizeHtml.defaults.allowedTags.concat([
          'img', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 's', 'u',
          'table', 'thead', 'tbody', 'tr', 'th', 'td', 'hr',
          'ul', 'ol', 'li', 'blockquote', 'sup', 'sub', 'figcaption'
        ]),
        allowedAttributes: {
          ...sanitizeHtml.defaults.allowedAttributes,
          img: ['src', 'alt', 'width', 'height'],
          th: ['colspan', 'rowspan'],
          td: ['colspan', 'rowspan'],
          p: ['style', 'class'],
          hr: ['class'],
          h1: ['style'],
          h2: ['style'],
          h3: ['style'],
          h4: ['style'],
          h5: ['style'],
          h6: ['style']
        },
        allowedSchemes: ['http', 'https', 'data'],
      });
    } catch (e) {
      throw new Error(`Sanitization failed: ${e.message}`);
    }

    // 3. Normalization (Req 8)
    try {
      const $ = cheerio.load(cleanHtml, null, false);
      
      // Remove empty paragraphs
      $('p').each(function() {
        const text = $(this).text().trim();
        const hasImg = $(this).find('img').length > 0;
        if (text === '' && !hasImg) {
          $(this).remove();
        }
      });
      
      // Remove inline styles we don't support, keep text-align
      $('[style]').each(function() {
        const style = $(this).attr('style');
        if (style && style.includes('text-align')) {
          // Keep it
        } else {
          $(this).removeAttr('style');
        }
      });

      cleanHtml = $.html();
    } catch (e) {
      console.warn('[DocumentIRToTiptap] Normalization warning:', e.message);
    }

    // 4. Generate Tiptap JSON
    let tiptapJson;
    try {
      tiptapJson = generateJSON(cleanHtml, getTiptapExtensions());
      
      // Ensure at least one paragraph exists if empty (Tiptap schema requirement)
      if (!tiptapJson.content || tiptapJson.content.length === 0) {
        tiptapJson.content = [{ type: 'paragraph' }];
      }
    } catch (e) {
      throw new Error(`Tiptap conversion failed: ${e.message}`);
    }
    
    // 5. Extract plain text
    const extractText = (node) => {
      let text = '';
      if (node.type === 'text') {
        text += node.text;
      } else if (node.type === 'image') {
        text += ' [Image] ';
      }
      if (node.content) {
        node.content.forEach((child) => {
          text += extractText(child);
        });
      }
      if (node.type === 'paragraph' || node.type?.startsWith('heading')) {
        text += '\n\n';
      }
      return text;
    };

    const plainText = extractText(tiptapJson).trim();

    return {
      tiptapJson,
      contentHtml: cleanHtml,
      plainText,
    };
  }
}

export default DocumentIRToTiptap;
